#Atualização do Docker-compose.yml (dentro da pasta trajeto)]
#Você vai rodar dois containers: um para staging (teste) e outro para produção, cada um em uma porta diferente.


version: '3.8'

services:
  trajeto-staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trajeto-staging
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging

  trajeto-production:
    image: trajeto-app:latest
    container_name: trajeto-production
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - trajeto-staging
